##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Tue Jan 03 11:25:56 CST 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

BSP	?= mcu-bsp

######################################
# target
######################################
TARGET = VICOMTEST


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/main.c \
src/stm32l0xx_it.c \
src/stm32l0xx_hal_msp.c \
${BSP}/CMSIS/Device/ST/STM32L0xx/Source/system_stm32l0xx.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_adc_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_adc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_comp_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_comp.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_cortex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_crc_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_crc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_cryp_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_cryp.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_dac_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_dac.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_dma.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_exti.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_firewall.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_flash_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_flash_ramfunc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_flash.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_gpio.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_i2c_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_i2c.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_i2s.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_irda.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_iwdg.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_lcd.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_lptim.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_pcd_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_pcd.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_pwr_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_pwr.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_rcc_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_rcc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_rng.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_rtc_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_rtc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_smartcard_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_smartcard.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_smbus_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_smbus.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_spi.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_tim_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_tim.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_tsc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_uart_ex.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_uart.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_usart.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_wwdg.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_adc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_comp.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_crc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_crs.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_dac.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_dma.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_exti.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_gpio.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_i2c.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_lptim.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_lpuart.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_pwr.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_rcc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_rng.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_rtc.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_spi.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_tim.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_usart.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_usb.c \
${BSP}/peripherals/stm32l0xx/src/stm32l0xx_ll_utils.c \
${BSP}/lib/src/viccom_stm32l0xx.c \
# ${BSP}/CMSIS/peripherals/stm32l0xx/src/... \
# ${BSP}/CMSIS/Device/ST/Source/gcc/... \
# ${BSP}/peripherals/stm32l0xx/src/stm32l0xx_hal_msp_template.c \

# ASM sources
ASM_SOURCES =  \
${BSP}/CMSIS/Device/ST/STM32L0xx/Source/gcc/startup_stm32l011xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0plus

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L011xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Iinc \
-I${BSP}/peripherals/stm32l0xx/inc \
-I${BSP}/peripherals/stm32l0xx/inc/Legacy \
-I${BSP}/CMSIS/Device/ST/STM32L0xx/Include \
-I${BSP}/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = ${BSP}/CMSIS/Device/ST/STM32L0xx/Source/gcc/STM32L011K4Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-del /q /s $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***